/**
 * GFBDecoder.test.mjs — Comprehensive tests for GFB v2 decoder.
 * Uses the golden fixture generated by the Rust encoder test suite.
 * Run: node --test lib/packages/core/src/layers/GFBDecoder.test.mjs
 */
import { describe as describeBase, it as itBase } from 'vitest';
import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';
import { resolve, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';
import { decodeGFB } from './GFBDecoder.js';

const __dirname = dirname(fileURLToPath(import.meta.url));
const fixturePath = resolve(
  __dirname,
  '../../../../../services/flexstream/tests/fixtures/golden_gfb_all_types.gfb'
);

let golden = null;
try {
  const buf = readFileSync(fixturePath);
  golden = decodeGFB(buf.buffer.slice(buf.byteOffset, buf.byteOffset + buf.byteLength));
} catch (e) {
  console.warn(`⚠ Golden GFB fixture not found at ${fixturePath} — skipping decoder tests.`);
  console.warn(
    '  Generate it with: cd services/flexstream && cargo test --release --lib test_generate_golden_fixture -- --nocapture'
  );
}

// Skip (don't fail) the decoder suite when the Rust-generated fixture is absent,
// so `node --test src/` stays green on a JS-only checkout. Full coverage runs
// whenever the fixture is present.
const describe = golden ? describeBase : describeBase.skip;
const it = golden ? itBase : itBase.skip;

// ── Expected golden values (must match Rust test_generate_golden_fixture) ──
// 2 entities: entity_alpha, entity_beta
// 2 epochs, interval=10, fpp=3 (3D)
// Static: id(string), label(string), score_f32, score_f64, count_i32, flags_u32, priority(u8)
// Temporal: speed(f32), status(string)

describe('GFB v2 Header', () => {
  it('decodes magic and version', () => {
    // If we got here, decodeGFB didn't throw → magic is 'GFB2'
    assert.ok(golden, 'Golden fixture decoded');
  });

  it('decodes feature count', () => {
    assert.equal(golden.featureCount, 2);
  });

  it('decodes geometry type', () => {
    assert.equal(golden.geomType, 1); // POINT
  });

  it('decodes fpp and altitude flag', () => {
    assert.equal(golden.hasAltitude, true);
  });

  it('decodes epoch count and interval', () => {
    assert.equal(golden.epochCount, 2);
    assert.equal(golden.epochInterval, 10);
  });

  it('has temporal and dictionary flags', () => {
    assert.equal(golden.hasTemporal, true);
    assert.equal(golden.geomIsTemporal, true);
  });

  it('has bbox', () => {
    assert.ok(golden.bbox, 'bbox should exist');
    // Positions: (10.5,30.5), (20.5,40.5) epoch0; (11.5,31.5), (21.5,41.5) epoch1
    assert.ok(golden.bbox.minLon <= 10.5 + 0.1);
    assert.ok(golden.bbox.maxLon >= 21.5 - 0.1);
    assert.ok(golden.bbox.minLat <= 30.5 + 0.1);
    assert.ok(golden.bbox.maxLat >= 41.5 - 0.1);
  });
});

describe('GFB v2 Dictionary', () => {
  it('has entries', () => {
    assert.ok(golden.dictionary, 'dictionary should exist');
    assert.ok(golden.dictionary.length >= 6, `dict too small: ${golden.dictionary.length}`);
  });

  it('contains entity keys', () => {
    assert.ok(golden.dictionary.includes('entity_alpha'));
    assert.ok(golden.dictionary.includes('entity_beta'));
  });

  it('contains static string values', () => {
    assert.ok(golden.dictionary.includes('cat_a'));
    assert.ok(golden.dictionary.includes('cat_b'));
  });

  it('contains temporal string values', () => {
    assert.ok(golden.dictionary.includes('active'));
    assert.ok(golden.dictionary.includes('idle'));
  });

  it('has no duplicates', () => {
    const unique = new Set(golden.dictionary);
    assert.equal(unique.size, golden.dictionary.length, `duplicates: ${golden.dictionary}`);
  });
});

describe('GFB v2 Entity IDs', () => {
  it('resolves entity key name', () => {
    assert.equal(golden.entityKey, 'id');
  });

  it('resolves entity ID strings', () => {
    assert.ok(golden.entityIds, 'entityIds should exist');
    assert.equal(golden.entityIds.length, 2);
    assert.ok(golden.entityIds.includes('entity_alpha'));
    assert.ok(golden.entityIds.includes('entity_beta'));
  });
});

describe('GFB v2 Geometry (3D temporal)', () => {
  it('has temporal point geometry', () => {
    assert.ok(golden.geometry, 'geometry should exist');
    assert.equal(golden.geometry.type, 'temporal_point');
    assert.equal(golden.geometry.floatsPerPos, 3);
  });

  it('has correct position count', () => {
    // 2 epochs × 2 entities × 3 fpp = 12 floats
    assert.equal(golden.geometry.positions.length, 12);
  });

  it('epoch 0 positions match', () => {
    const p = golden.geometry.positions;
    // Entity 0 (alpha): lon=10.5, lat=30.5, alt=5000
    assert.ok(Math.abs(p[0] - 10.5) < 0.1, `e0 alpha lon: ${p[0]}`);
    assert.ok(Math.abs(p[1] - 30.5) < 0.1, `e0 alpha lat: ${p[1]}`);
    assert.ok(Math.abs(p[2] - 5000.0) < 1, `e0 alpha alt: ${p[2]}`);
    // Entity 1 (beta): lon=20.5, lat=40.5, alt=6000
    assert.ok(Math.abs(p[3] - 20.5) < 0.1, `e0 beta lon: ${p[3]}`);
    assert.ok(Math.abs(p[4] - 40.5) < 0.1, `e0 beta lat: ${p[4]}`);
  });
});

describe('GFB v2 Static Columns — All Types', () => {
  it('has label (DICT_STRING → u16)', () => {
    const col = golden.staticColumns.label;
    assert.ok(col, 'label column missing');
    assert.equal(col.length, 2);
    // u16 indices — resolve via dictionary
    const v0 = golden.dictionary[col[0]];
    const v1 = golden.dictionary[col[1]];
    assert.equal(v0, 'cat_a');
    assert.equal(v1, 'cat_b');
  });

  it('has score_f32 (Float32)', () => {
    const col = golden.staticColumns.score_f32;
    assert.ok(col instanceof Float32Array);
    assert.ok(Math.abs(col[0] - 1.5) < 0.01);
    assert.ok(Math.abs(col[1] - 2.5) < 0.01);
  });

  it('has score_f64 (Float64)', () => {
    const col = golden.staticColumns.score_f64;
    assert.ok(col instanceof Float64Array);
    assert.ok(Math.abs(col[0] - 100.1) < 0.01);
    assert.ok(Math.abs(col[1] - 200.2) < 0.01);
  });

  it('has count_i32 (Int32)', () => {
    const col = golden.staticColumns.count_i32;
    assert.ok(col instanceof Int32Array);
    assert.equal(col[0], -42);
    assert.equal(col[1], 99);
  });

  it('has flags_u32 (Uint32)', () => {
    const col = golden.staticColumns.flags_u32;
    assert.ok(col instanceof Uint32Array);
    assert.equal(col[0], 0xff);
    assert.equal(col[1], 0x100);
  });

  it('has priority (Uint8)', () => {
    const col = golden.staticColumns.priority;
    assert.ok(col instanceof Uint8Array);
    assert.equal(col[0], 1);
    assert.equal(col[1], 255);
  });
});

describe('GFB v2 Temporal Columns', () => {
  it('has speed (Float32, epoch-major)', () => {
    const col = golden.temporalColumns.speed;
    assert.ok(col instanceof Float32Array);
    // 2 epochs × 2 entities = 4 values
    assert.equal(col.length, 4);
    // epoch0: e0=500, e1=600; epoch1: e0=550, e1=650
    assert.ok(Math.abs(col[0] - 500.0) < 0.1); // alpha ep0
    assert.ok(Math.abs(col[1] - 600.0) < 0.1); // beta ep0
    assert.ok(Math.abs(col[2] - 550.0) < 0.1); // alpha ep1
    assert.ok(Math.abs(col[3] - 650.0) < 0.1); // beta ep1
  });

  it('has status (DICT_STRING → u16, epoch-major)', () => {
    const col = golden.temporalColumns.status;
    assert.ok(col instanceof Uint16Array);
    assert.equal(col.length, 4);
    // epoch0: alpha=active, beta=idle; epoch1: alpha=idle, beta=active
    assert.equal(golden.dictionary[col[0]], 'active');
    assert.equal(golden.dictionary[col[1]], 'idle');
    assert.equal(golden.dictionary[col[2]], 'idle');
    assert.equal(golden.dictionary[col[3]], 'active');
  });
});

describe('GFB v2 u32→u16 Dict Index Downcast', () => {
  it('preserves valid indices', () => {
    // All dict indices in the golden fixture should be < dictionary.length
    for (const [name, col] of Object.entries(golden.staticColumns)) {
      if (col instanceof Uint16Array) {
        for (let i = 0; i < col.length; i++) {
          assert.ok(
            col[i] < golden.dictionary.length || col[i] === 0xffff,
            `${name}[${i}] = ${col[i]} out of range`
          );
        }
      }
    }
  });
});
